EC2 deploy script active again

diff --git a/.github/workflows/EC2.yml b/.github/workflows/EC2.yml
--- a/.github/workflows/EC2.yml
+++ b/.github/workflows/EC2.yml
@@ -9,7 +9,18 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
-    
+
+    - name: Stop remote containers
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.REMOTE_HOST }}
+        username: ${{ secrets.REMOTE_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          cd /home/${{ secrets.REMOTE_USER }}/apigo
+          docker compose down
+
     - name: Deploy to Staging server
       uses: easingthemes/ssh-deploy@main
       env:
@@ -18,8 +29,12 @@ jobs:
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         TARGET: /home/${{ secrets.REMOTE_USER }}/apigo
         EXCLUDE: "postgres-data"
-    # TODO: update below to run go app with docker compose...
-    - name: executing remote ssh commands using password
+        args: |
+          -avz --delete
+          --include "docker-compose.yml"
+          --exclude "*"
+
+    - name: Start remote containers
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.REMOTE_HOST }}
@@ -33,8 +48,11 @@ jobs:
           export DBNAME=${{ secrets.DBNAME }}
           export DBPORT=${{ secrets.DBPORT }}
           export PORT=8000
-          chmod +x /home/${{ secrets.REMOTE_USER }}/apigo/main
           cd /home/${{ secrets.REMOTE_USER }}/apigo
-          nohup ./main > nohup.out 2> nohup.err < /dev/null &
-        
+          docker compose up -d > docker-compose-logs.txt 2>&1
+          if [ $? -eq 0 ]; then
+            echo "Docker Compose command succeeded."
+          else
+            echo "Docker Compose command failed."
+          fi
         
